fix: remove invalid await on sync _dispatch_scan_phase call
_dispatch_scan_phase is a regular (non-async) function that calls
scan_phase_task.delay() synchronously. Calling it with await caused
TypeError: object NoneType can't be used in 'await' expression
when creating a scan (POST /api/v1/scans returned 500).